### ISSUE TITLE
Add twig settings to config.yml

### ISSUE THREAD

**Issue by manuelkleinert** [w-vision/Wvision#28]
```
twig:
    globals:
        kernelPublicDir: '%kernel.project_dir%/web/'
    form_themes:
        - 'Form/uikit_3_layout.html.twig'
```
